### ISSUE TITLE
flow to image

### ISSUE THREAD

**Issue by TengFeiHan0** [cattaneod/MaskFlownet-Pytorch#1]
I run your code and trying to generate an output image. However, my result is very bad. I guess that the conversion from flow tensor to an image is wrong in my implementation, would you mind showing your code or some samples?

**Comment by TengFeiHan0** [comment]
I already fix it, thank you for opening code

**Comment by cattaneod** [comment]
Hi,
I'm glad that you solved.
Anyway, I used this code to visualize the optical flow: https://github.com/tomrunia/OpticalFlow_Visualization

**Comment by TengFeiHan0** [comment]
Thank you for your reply. As your can see below, I obtained a much clear results than other methods before. However, how to incorporate `occ_mask` and our predicted flow? 
![1](https://user-images.githubusercontent.com/38068286/85658139-dda05c80-b6ed-11ea-8317-1020f73db8f9.png)

**Comment by cattaneod** [comment]
I'm not the author of the paper, i only made the pytorch porting.
For any questions related to the approach, you should ask the authors of the paper, the official implementation is here: https://github.com/microsoft/MaskFlownet

**Comment by TengFeiHan0** [comment]
@cattaneod I'm sorry to ask you for help. I'm going to build a training pipeline based on your code. 

I got a problem when computing the `EpeLoss`. When executing on this [line](https://github.com/cattaneod/MaskFlownet-Pytorch/blob/master/model/MaskFlownet.py#L682), 

Ideally, it should return a tensor includes a **single** element.  
Actually, it returns a tensor includes **four** elements on each GPU(my batch_size is 4). So my loss couldn't be backward. 
```
tensor([1.8977, 2.0039, 1.7233, 1.5050], device='cuda:0',
       grad_fn=<AddBackward0>)
```
how about your training process?
if possible,  any cues would be highly appreciated.

**Comment by cattaneod** [comment]
Hi,
the function return the EPE for every sample in the batch. If you want to backward it than you can just take the mean:
```
loss = EpeLossWithMask()(up_flow, label, mask).mean()
loss.backward()
```

If you want to use the Multi Scale loss, then similarly:
```
loss = MultiscaleEpe([64, 32, 16, 8, 4], [.005, .01, .02, .08, .32], 'upsampling', eps = 1e-8)(up_flow, label, mask).mean()
loss.backward()
```

**Comment by TengFeiHan0** [comment]
hi, yesterday, I already did as you said, I got an error like this 

```
File "/home/fei/maskflownet/models/model.py", line 84, in step
    loss.backward()
  File "/home/fei/anaconda3/envs/flow/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/fei/anaconda3/envs/flow/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: function CorrelationFunctionBackward returned an incorrect number of gradients (expected 8, got 2)
```

![Screenshot from 2020-06-30 12-27-01](https://user-images.githubusercontent.com/38068286/86080099-0e590b00-bacd-11ea-85f0-f6ac17b71f7b.png)
I haven't found any useful info on google. If possible, Could you show the key points of your training pipeline?

**Comment by cattaneod** [comment]
Hi,
for some reason, the backward of the correlation is broken.
In my training i used a different correlation implementation, but then the results with the original weights are different, I will fix it today or tomorrow.

Thank you for pointing this out.

**Comment by TengFeiHan0** [comment]
what's this problem of your correlation package? could you share more details about this? I'd like to fix it. @cattaneod

**Comment by cattaneod** [comment]
Ok, i solved the backward problem of the correlation package i was using, just replace line 52 of model/correlation_package/correlation.py with:
```
return grad_input1, grad_input2, None, None, None, None, None, None
```
